GET http://localhost:3333
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQ5MjU1NTAsImV4cCI6MTY4NjQ4MzE1MCwiYXVkIjoiNjJhMzFlMjdlMWYwNGZlNjhmMTE4MDg4IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.LopeZSceTiV7ONR599jSg12mddcAe3GPXKnDkMWD1YI

###Login Route
POST http://localhost:3333/api/v1/login
Content-Type: application/json


{
  "email": "saadk447@gmail.com",
  "password": "1234"
}



###Register Route
POST http://localhost:3333/api/v1/register
Content-Type: application/json

{
  "email": "saadk9632@gmail.com",
  "password": "1234"
}

###Refresh token Route
POST http://localhost:3333/api/v1/refresh-token
Content-Type: application/json


{
"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQ5MzIxNzQsImV4cCI6MTY4NjQ4OTc3NCwiYXVkIjoiNjJhNDQyY2UxNzViN2NmOTA3YWY5Mjg5IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.bLOt8RdKVj3PZMHYFWQeRIwn-LN8EXPd_Uze8ZgPE2I"
}

###Logout Route
DELETE http://localhost:3333/api/v1/logout
Content-Type: application/json

{
"refreshToken":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQ5MzIyNzIsImV4cCI6MTY4NjQ4OTg3MiwiYXVkIjoiNjJhMzFlMjdlMWYwNGZlNjhmMTE4MDg4IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.B79Y986df6y5tNoYoMITeYEtYG0R1pHYq5O6GBJ8l5U"
}
